[connections.sqlite]
url = 'sqlite:///mydb.db'

[connections.mssql]
url = 'mssql+pymssql://sa:Password!@localhost:1433/mydb'

pymssql, pyodbc

- Host: localhost
- Port: 1433
- Database: mydb
- Username: sa
- Password: Password!

wuttichaihung
